<?php

use App\Graph\Region;

return [
    [
        'group' => 6,
        'name' => "Agahnims Tower - Entrance",
        'roomid' => 0xE0,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Chain Guards",
        'roomid' => 0xE0,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Knife Guards",
        'roomid' => 0xE0,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - First Chest",
        'type' => 'chest',
        'addresses' => [0xEAB5],
        'itemset' => ['agahnim']
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - First Door",
        'type' => 'keydoor',
        'key' => 'KeyA1',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Keese Statue darkness",
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Keese Statue",
        'roomid' => 0xD0,
        'layout' => Region::TOP_RIGHT,
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Dark Maze",
        'roomid' => 0xD0,
        'layout' => Region::LEFT,
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Second Chest",
        'type' => 'chest',
        'addresses' => [0xEAB2],
        'itemset' => ['agahnim']
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Second Door",
        'type' => 'keydoor',
        'key' => 'KeyA1',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Dark Knife Guards",
        'roomid' => 0xD0,
        'layout' => Region::BOTTOM_RIGHT,
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Dark Corner",
        'roomid' => 0xC0,
        'layout' => Region::BOTTOM_RIGHT,
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Dark Bridge",
        'roomid' => 0xC0,
        'layout' => Region::LEFT,
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Dark Key Guards",
        'roomid' => 0xC0,
        'layout' => Region::TOP_RIGHT,
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'roomid' => 0xC0,
        'layout' => Region::TOP_RIGHT,
        'name' => "Agahnims Tower - Archer Key - Left Archer",
        'type' => 'mob',
        'item' => 'KeyA1',
        'itemset' => ['agahnim'],
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Third Door",
        'type' => 'keydoor',
        'key' => 'KeyA1',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Dark Key Guards darkness",
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Throwing Guards",
        'roomid' => 0xB0,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Guards",
        'roomid' => 0xB0,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Circle of Pots",
        'roomid' => 0xB0,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'roomid' => 0xB0,
        'layout' => Region::BOTTOM_LEFT,
        'name' => "Agahnims Tower - Guard Key - Center Guard",
        'type' => 'mob',
        'item' => 'KeyA1',
        'itemset' => ['agahnim'],
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Fourth Door",
        'type' => 'keydoor',
        'key' => 'KeyA1',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Guard Mix",
        'roomid' => 0xB0,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Push Statue",
        'roomid' => 0x40,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Bridge",
        'roomid' => 0x40,
        'layout' => Region::LEFT,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Antichamber",
        'roomid' => 0x30,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Bedroom",
        'roomid' => 0x30,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Boss Room",
        'roomid' => 0x20,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 6,
        'name' => "Agahnims Tower - Boss",
        'type' => 'event',
        'item' => 'AgahnimDefeated',
        'itemset' => ['event'],
    ],
];
