<?php

use App\Graph\Region;

return [
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Left",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Right",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Compass Room Door",
        'roomid' => 0x85,
        'type' => 'keydoor',
        'key' => 'KeyP2',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Compass Room",
        'roomid' => 0x85,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Hallway",
        'roomid' => 0x85,
        'layout' => Region::LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Northeast Corner",
        'roomid' => 0x75,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Trap Room",
        'roomid' => 0x75,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Big Key Chest",
        'roomid' => 0x75,
        'layout' => Region::RIGHT,
        'addresses' => [0xE9C2],
        'type' => 'chest',
        'itemset' => ['desert'],
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Map Chest",
        'addresses' => [0xE9B6],
        'roomid' => 0x74,
        'layout' => Region::TOP,
        'type' => 'chest',
        'itemset' => ['desert'],
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Northwest Corner",
        'roomid' => 0x73,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'roomid' => 0x73,
        'layout' => Region::BOTTOM_LEFT,
        'name' => "Desert Palace - Beemos Room",
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Big Chest Room",
        'roomid' => 0x73,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Big Chest",
        'addresses' => [0xE98F],
        'type' => 'bigchest',
        'itemset' => ['desert'],
    ],
    [
        'group' => 3,
        'roomid' => 0x73,
        'layout' => Region::TOP_RIGHT,
        'name' => "Desert Palace - Torch Room",
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Torch",
        'addresses' => [0x180160],
        'type' => 'bonk',
        'itemset' => ['desert'],
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Compass Chest",
        'addresses' => [0xE9CB],
        'type' => 'chest',
        'itemset' => ['desert'],
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Left Hallway",
        'roomid' => 0x83,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Fairies",
        'roomid' => 0x83,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 4,
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'name' => "Desert Palace - Beemos 2",
        'type' => 'region',
    ],
    [
        'group' => 4,
        'roomid' => 0x63,
        'layout' => Region::TOP_LEFT,
        'name' => "Desert Palace - Tiles 1",
        'type' => 'region',
    ],
    [
        'group' => 4,
        'roomid' => 0x63,
        'location' => 0x1c17,
        'layout' => Region::TOP_LEFT,
        'name' => "Desert Palace - Tiles 1 - BL Pot",
        'type' => 'pot',
        'item' => 'KeyP2',
        'itemset' => ['desert'],
    ],
    [
        'group' => 4,
        'name' => "Desert Palace - Tiles 1 Door",
        'type' => 'keydoor',
        'key' => 'KeyP2',
    ],
    [
        'group' => 4,
        'roomid' => 0x53,
        'layout' => Region::TOP_LEFT,
        'name' => "Desert Palace - Bridge",
        'type' => 'region',
    ],
    [
        'group' => 4,
        'roomid' => 0x53,
        'layout' => Region::BOTTOM_LEFT,
        'name' => "Desert Palace - Popo Genocide",
        'type' => 'region',
    ],
    [
        'group' => 4,
        'roomid' => 0x53,
        'layout' => Region::RIGHT,
        'name' => "Desert Palace - Popo Hallway Bottom",
        'type' => 'region',
    ],
    [
        'group' => 4,
        'roomid' => 0x53,
        'layout' => Region::RIGHT,
        'name' => "Desert Palace - Popo Hallway - Pot",
        'type' => 'pot',
        'item' => 'KeyP2',
        'itemset' => ['desert'],
    ],
    [
        'group' => 4,
        'roomid' => 0x53,
        'layout' => Region::RIGHT,
        'name' => "Desert Palace - Popo Hallway Top",
        'type' => 'region',
    ],
    [
        'group' => 4,
        'name' => "Desert Palace - Popo Hallway Door",
        'type' => 'keydoor',
        'key' => 'KeyP2',
    ],
    [
        'group' => 4,
        'roomid' => 0x43,
        'layout' => Region::BOTTOM_RIGHT,
        'name' => "Desert Palace - Tiles 2",
        'type' => 'region',
    ],
    [
        'group' => 4,
        'roomid' => 0x43,
        'layout' => Region::BOTTOM_RIGHT,
        'name' => "Desert Palace - Tiles 2 - TR Pot",
        'type' => 'pot',
        'item' => 'KeyP2',
        'itemset' => ['desert'],
    ],
    [
        'group' => 4,
        'name' => "Desert Palace - Tiles 2 Door",
        'type' => 'keydoor',
        'key' => 'KeyP2',
    ],
    [
        'group' => 4,
        'roomid' => 0x43,
        'layout' => Region::TOP,
        'name' => "Desert Palace - Sliding Wall",
        'type' => 'region',
    ],
    [
        'group' => 4,
        'name' => "Desert Palace - Sliding Wall Door",
        'type' => 'bigkeydoor',
        'key' => 'BigKeyP2',
    ],
    [
        'group' => 4,
        'name' => "Desert Palace - Boss Room",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
    ],
    [
        'group' => 4,
        'name' => "Desert Palace - Boss",
        'addresses' => [0x180151],
        'type' => 'drop',
        'itemset' => ['desert'],
    ],
    [
        'group' => 4,
        'name' => "Desert Palace - Prize",
        'addresses' => [null, 0x1209E, 0x53F1C, 0x53F1D, 0x180053, 0x180078, 0xC6FF],
        'type' => 'prize',
        'itemset' => ['prize'],
    ],
];
