<?php

use App\Graph\Region;

return [
    // Desert Palace Main Entrance
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Bunny",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Cave State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Hyrule Castle State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Sewers State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Eastern Palace State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Tower of Hera State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Agahnims Tower State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Palace of Darkness State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Swamp Palace State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Skull Woods State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Thieves Town State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Ice Palace State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Misery Mire State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Turtle Rock State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Ganons Tower State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    //Desert Palace Right Entrance
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Bunny",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Cave State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Hyrule Castle State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Sewers State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Eastern Palace State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Tower of Hera State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Agahnims Tower State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Palace of Darkness State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Swamp Palace State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Skull Woods State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Thieves Town State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Ice Palace State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Misery Mire State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Turtle Rock State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Ganons Tower State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    // Desert Palace Left Entrance
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Bunny",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Cave State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Hyrule Castle State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Sewers State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Eastern Palace State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Tower of Hera State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Agahnims Tower State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Palace of Darkness State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Swamp Palace State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Skull Woods State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Thieves Town State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Ice Palace State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Misery Mire State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Turtle Rock State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Ganons Tower State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    // Desert Palace Back Entrance
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Bunny",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Cave State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Hyrule Castle State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Sewers State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Eastern Palace State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Tower of Hera State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Agahnims Tower State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Palace of Darkness State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Swamp Palace State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Skull Woods State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Thieves Town State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Ice Palace State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Misery Mire State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Turtle Rock State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Ganons Tower State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    // Desert Palace Boss Room
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Eastern Palace State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Tower of Hera State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Palace of Darkness State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Swamp Palace State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Skull Woods State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Thieves Town State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Ice Palace State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Misery Mire State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Turtle Rock State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
];
