<?php

use App\Graph\Region;

return [
    // Hyrule Castle Lobby Entrance
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Bunny",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Cave State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Sewers State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Eastern Palace State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Desert Palace State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Tower of Hera State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Agahnims Tower State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Palace of Darkness State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Swamp Palace State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Skull Woods State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Thieves Town State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Ice Palace State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Misery Mire State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Turtle Rock State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby - Ganons Tower State",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    // Hyrule Castle East Entrance
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Bunny",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Cave State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Sewers State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Eastern Palace State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Desert Palace State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Tower of Hera State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Agahnims Tower State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Palace of Darkness State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Swamp Palace State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Skull Woods State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Thieves Town State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Ice Palace State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Misery Mire State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Turtle Rock State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East - Ganons Tower State",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    // Hyrule Castle West Entrance
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Bunny",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Cave State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Sewers State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Eastern Palace State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Desert Palace State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Tower of Hera State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Agahnims Tower State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Palace of Darkness State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Swamp Palace State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Skull Woods State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Thieves Town State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Ice Palace State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Misery Mire State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Turtle Rock State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West - Ganons Tower State",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    // Hyrule Castle Throne Room
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Bunny",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Cave State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Sewers State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Eastern Palace State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Desert Palace State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Tower of Hera State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Agahnims Tower State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Palace of Darkness State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Swamp Palace State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Skull Woods State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Thieves Town State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Ice Palace State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Misery Mire State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Turtle Rock State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room - Ganons Tower State",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    // Sewers Entry
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Cave State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Hyrule Castle State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Eastern Palace State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Desert Palace State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Tower of Hera State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Agahnims Tower State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Palace of Darkness State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Swamp Palace State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Skull Woods State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Thieves Town State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Ice Palace State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Misery Mire State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Turtle Rock State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus - Ganons Tower State",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    // Sanctuary Entrance
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Bunny",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Cave State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Hyrule Castle State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Eastern Palace State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Desert Palace State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Tower of Hera State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Agahnims Tower State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Palace of Darkness State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Swamp Palace State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Skull Woods State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Thieves Town State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Ice Palace State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Misery Mire State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Turtle Rock State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall - Ganons Tower State",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    // Eastern Palace Entrance
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Bunny",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Cave State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Hyrule Castle State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Sewers State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Eastern Palace State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Tower of Hera State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Agahnims Tower State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Palace of Darkness State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Swamp Palace State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Skull Woods State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Thieves Town State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Ice Palace State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Misery Mire State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Turtle Rock State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance - Ganons Tower State",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    // Eastern Palace Boss Room
    [
        'group' => 3,
        'name' => "Eastern Palace - Boss Room - Desert Palace State",
        'roomid' => 0xC8,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Eastern Palace - Boss Room - Tower of Hera State",
        'roomid' => 0xC8,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Eastern Palace - Boss Room - Palace of Darkness State",
        'roomid' => 0xC8,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Eastern Palace - Boss Room - Swamp Palace State",
        'roomid' => 0xC8,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Eastern Palace - Boss Room - Skull Woods State",
        'roomid' => 0xC8,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Eastern Palace - Boss Room - Thieves Town State",
        'roomid' => 0xC8,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Eastern Palace - Boss Room - Ice Palace State",
        'roomid' => 0xC8,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Eastern Palace - Boss Room - Misery Mire State",
        'roomid' => 0xC8,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Eastern Palace - Boss Room - Turtle Rock State",
        'roomid' => 0xC8,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    // Desert Palace Main Entrance
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Bunny",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Cave State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Hyrule Castle State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Sewers State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Eastern Palace State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Tower of Hera State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Agahnims Tower State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Palace of Darkness State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Swamp Palace State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Skull Woods State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Thieves Town State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Ice Palace State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Misery Mire State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Turtle Rock State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Main Room - Center - Ganons Tower State",
        'roomid' => 0x84,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    //Desert Palace Right Entrance
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Bunny",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Cave State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Hyrule Castle State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Sewers State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Eastern Palace State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Tower of Hera State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Agahnims Tower State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Palace of Darkness State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Swamp Palace State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Skull Woods State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Thieves Town State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Ice Palace State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Misery Mire State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Turtle Rock State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Right Entrance - Ganons Tower State",
        'roomid' => 0x85,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    // Desert Palace Left Entrance
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Bunny",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Cave State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Hyrule Castle State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Sewers State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Eastern Palace State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Tower of Hera State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Agahnims Tower State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Palace of Darkness State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Swamp Palace State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Skull Woods State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Thieves Town State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Ice Palace State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Misery Mire State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Turtle Rock State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos Torches - Ganons Tower State",
        'roomid' => 0x83,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],/*
    // Desert Palace North Hallway Room
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Cave State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Hyrule Castle State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Sewers State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Eastern Palace State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Tower of Hera State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Agahnims Tower State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Palace of Darkness State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Swamp Palace State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Skull Woods State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Thieves Town State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Ice Palace State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Misery Mire State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Turtle Rock State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - North Hallway - Ganons Tower State",
        'roomid' => 0x74,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],*/
    // Desert Palace Back Entrance
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Bunny",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Cave State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Hyrule Castle State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Sewers State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Eastern Palace State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Tower of Hera State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Agahnims Tower State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Palace of Darkness State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Swamp Palace State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Skull Woods State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Thieves Town State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Ice Palace State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Misery Mire State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Turtle Rock State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Beemos 2 - Ganons Tower State",
        'roomid' => 0x63,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    // Desert Palace Boss Room
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Eastern Palace State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Tower of Hera State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Palace of Darkness State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Swamp Palace State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Skull Woods State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Thieves Town State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Ice Palace State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Misery Mire State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 3,
        'name' => "Desert Palace - Boss Room - Turtle Rock State",
        'roomid' => 0x33,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
];
