<?php

use App\Graph\Region;

return [
    [
        'group' => 2,
        'name' => "Eastern Palace - Entrance",
        'roomid' => 0xC9,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Popo Switch",
        'roomid' => 0xC9,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Cannonball Room",
        'roomid' => 0xB9,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Cannonball Chest",
        'type' => 'chest',
        'addresses' => [0xE9B3],
        'itemset' => ['eastern'],
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Cannonball Bridge",
        'roomid' => 0xB9,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Main Room - Balcony",
        'roomid' => 0xA9,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - East Wing - Top",
        'roomid' => 0xAA,
        'layout' => Region::LEFT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - East Wing - Bottom",
        'roomid' => 0xAA,
        'layout' => Region::LEFT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - East Wing - Switch",
        'roomid' => 0xAA,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - East Wing - Gap Right",
        'roomid' => 0xAA,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Map Chest",
        'type' => 'chest',
        'addresses' => [0xE9F5],
        'itemset' => ['eastern'],
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - East Wing - Gap Left",
        'roomid' => 0xAA,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - West Wing - Top",
        'roomid' => 0xA8,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - West Wing - Bottom Tile",
        'roomid' => 0xA8,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - West Wing - Bottom",
        'roomid' => 0xA8,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - West Wing - Stalfos Ambush",
        'roomid' => 0xA8,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - West Wing - Corner",
        'roomid' => 0xA8,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Compass Chest",
        'type' => 'chest',
        'addresses' => [0xE977],
        'itemset' => ['eastern'],
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Main Room",
        'roomid' => 0xA9,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Big Chest",
        'type' => 'bigchest',
        'addresses' => [0xE97D],
        'itemset' => ['eastern'],
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Dark Antifairy Circle",
        'roomid' => 0xBA,
        'layout' => Region::TOP_LEFT,
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Dark Antifairy Circle darkness",
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Dark Stalfos",
        'roomid' => 0xBA,
        'layout' => Region::TOP_RIGHT,
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'roomid' => 0xBA,
        'layout' => Region::TOP_LEFT,
        'name' => "Eastern Palace - Dark Stalfos - TR Pot",
        'type' => 'pot',
        'item' => 'KeyP1',
        'itemset' => ['eastern'],
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Bridge Door",
        'type' => 'keydoor',
        'key' => 'KeyP1',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Antifairy Circle",
        'roomid' => 0xB8,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Big Key Chest",
        'type' => 'chest',
        'addresses' => [0xE9B9],
        'itemset' => ['eastern'],
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Main Room Door",
        'type' => 'bigkeydoor',
        'key' => 'BigKeyP1',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Dark Popos",
        'roomid' => 0x99,
        'layout' => Region::BOTTOM,
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Dark Popos darkness",
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Eyegore Key - Right Eyegore",
        'type' => 'mob',
        'item' => 'KeyP1',
        'itemset' => ['eastern'],
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Dark Cash",
        'roomid' => 0x99,
        'layout' => Region::TOP_RIGHT,
        'dark' => true,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Stairs Door",
        'type' => 'keydoor',
        'key' => 'KeyP1',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Antifairy Playground",
        'roomid' => 0xDA,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Eyegore Switches",
        'roomid' => 0xD9,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Dodgeball",
        'roomid' => 0xD9,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Kill Room 1",
        'roomid' => 0xD8,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Kill Room 2",
        'roomid' => 0xD8,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Boss Room",
        'roomid' => 0xC8,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Boss",
        'addresses' => [0x180150],
        'type' => 'drop',
        'itemset' => ['eastern'],
    ],
    [
        'group' => 2,
        'name' => "Eastern Palace - Prize",
        'addresses' => [null, 0x1209D, 0x53EF8, 0x53EF9, 0x180052, 0x18007C, 0xC6FE],
        'type' => 'prize',
        'itemset' => ['prize'],
    ],
];
