<?php

use App\Graph\Region;

return [
    [
        'group' => 1,
        'name' => "Secrect Passage Uncle",
        'roomid' => 0x55,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Link's Uncle",
        'type' => 'npc',
        'addresses' => [0x2DF45],
        'itemset' => ['escape'],
    ],
    [
        'group' => 1,
        'name' => "Secrect Passage Exit",
        'roomid' => 0x55,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Secret Passage",
        'type' => 'chest',
        'addresses' => [0xE971],
        'itemset' => ['escape'],
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Lobby",
        'roomid' => 0x61,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - East",
        'roomid' => 0x62,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - North East Passage",
        'roomid' => 0x52,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - West",
        'roomid' => 0x60,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - North West Passage",
        'roomid' => 0x50,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Throne Room",
        'roomid' => 0x51,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Back Passage",
        'roomid' => 0x01,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Statue",
        'roomid' => 0x72,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Statue - Guard Key",
        'roomid' => 0x72,
        'layout' => Region::TOP,
        'type' => 'mob',
        'item' => 'KeyH2',
        'itemset' => ['escape'],
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Map Chest",
        'type' => 'chest',
        'addresses' => [0xEB0C],
        'itemset' => ['escape'],
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Statue Door",
        'type' => 'keydoor',
        'key' => 'KeyH2',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Lonely Blue Guard",
        'roomid' => 0x72,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Lonely Blue Guard Overlook",
        'roomid' => 0x72,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Playpit",
        'roomid' => 0x82,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Playpit Overlook",
        'roomid' => 0x82,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Hallways",
        'roomid' => 0x81,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Trap",
        'roomid' => 0x71,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Statue Trap",
        'roomid' => 0x71,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Boomerang Chest",
        'type' => 'chest',
        'addresses' => [0xE974],
        'itemset' => ['escape'],
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Statue Trap - Guard Key",
        'roomid' => 0x71,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'mob',
        'item' => 'KeyH2',
        'itemset' => ['escape'],
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Trap Door",
        'type' => 'keydoor',
        'key' => 'KeyH2',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Post Trap",
        'roomid' => 0x71,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Cell Hall",
        'roomid' => 0x70,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Cells",
        'roomid' => 0x80,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Locked Cell",
        'roomid' => 0x80,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Cells - Ball N Chain Key",
        'roomid' => 0x80,
        'layout' => Region::TOP,
        'type' => 'mob',
        'item' => 'BigKeyH2',
        'itemset' => ['escape'],
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Zelda's Cell",
        'type' => 'chest',
        'addresses' => [0xEB09],
        'itemset' => ['escape'],
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Basement Cells - Zelda",
        'roomid' => 0x80,
        'layout' => Region::TOP,
        'type' => 'follower',
        'item' => 'LostZelda',
        'itemset' => ['event'],
    ],
    [
        'group' => 1,
        'name' => "Hyrule Castle - Mantle",
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus darkness",
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cactus",
        'roomid' => 0x41,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Rope Corridor",
        'roomid' => 0x42,
        'layout' => Region::TOP,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cross",
        'roomid' => 0x32,
        'layout' => Region::FULL,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cross Chest",
        'type' => 'chest',
        'addresses' => [0xE96E],
        'itemset' => ['escape'],
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Cross Door",
        'type' => 'keydoor',
        'key' => 'KeyH2',
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Three Islands",
        'roomid' => 0x22,
        'layout' => Region::BOTTOM,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark Aquabats",
        'roomid' => 0x21,
        'layout' => Region::BOTTOM,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark U",
        'roomid' => 0x21,
        'layout' => Region::TOP,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark U - Left Mouse",
        'roomid' => 0x21,
        'layout' => Region::TOP,
        'type' => 'mob',
        'item' => 'KeyH2',
        'itemset' => ['escape'],
    ],
    [
        'group' => 1,
        'name' => "Sewers - Dark U darkness",
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 1,
        'name' => "Sewers - Last Door",
        'type' => 'keydoor',
        'key' => 'KeyH2',
    ],
    [
        'group' => 1,
        'name' => "Sewers - Block Puzzle",
        'roomid' => 0x11,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sewers - Block Puzzle Top",
        'roomid' => 0x11,
        'layout' => Region::RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sewers - Secret Room",
        'roomid' => 0x11,
        'layout' => Region::LEFT,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sewers - Secret Room - Left",
        'type' => 'chest',
        'addresses' => [0xEB5D],
        'itemset' => ['escape'],
    ],
    [
        'group' => 1,
        'name' => "Sewers - Secret Room - Middle",
        'type' => 'chest',
        'addresses' => [0xEB60],
        'itemset' => ['escape'],
    ],
    [
        'group' => 1,
        'name' => "Sewers - Secret Room - Right",
        'type' => 'chest',
        'addresses' => [0xEB63],
        'itemset' => ['escape'],
    ],
    [
        'group' => 1,
        'name' => "Sewers - Rat Pots",
        'roomid' => 0x02,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sewers - Switch Puzzle",
        'roomid' => 0x02,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary - Princess Dropoff",
        'type' => 'event',
        'item' => 'RescueZelda',
        'itemset' => ['event'],
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Hall",
        'roomid' => 0x12,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 1,
        'name' => "Sanctuary Chest",
        'type' => 'chest',
        'addresses' => [0xEA79],
        'itemset' => ['escape'],
    ],
];
