<?php

use App\Graph\Region;

return [
    [
        'group' => 13,
        'name' => "Ice Palace - Entrance",
        'roomid' => 0x0E,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => "region",
        'peg' => 'orange',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Bari Key",
        'roomid' => 0x0E,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region"
    ],
    [
        'group' => 13,
        'roomid' => 0x0E,
        // figure out mob drop locations
        // 'location' => 0x1c17,
        'layout' => Region::BOTTOM_LEFT,
        'name' => "Ice Palace - Bari Key - Bottom Bari",
        'type' => 'mob',
        'item' => 'KeyD5',
        'itemset' => ['ice'],
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Bari Key Door",
        'type' => 'keydoor',
        'key' => 'KeyD5',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Blob Ambush",
        'roomid' => 0x1E,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region"
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Cross Puzzle - Left",
        'roomid' => 0x1E,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => "region"
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Cross Puzzle - Bottom",
        'roomid' => 0x1E,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => "region"
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Cross Puzzle - Right",
        'roomid' => 0x1E,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => "region"
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Cross Puzzle - Top",
        'roomid' => 0x1E,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => "region"
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Bomb Switch",
        'roomid' => 0x1E,
        'layout' => Region::TOP_RIGHT,
        'type' => "region"
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Penguin Switch",
        'roomid' => 0x1F,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region"
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Big Key View",
        'roomid' => 0x1F,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => "region"
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Penguin Chest",
        'roomid' => 0x2E,
        'layout' => Region::TOP_RIGHT,
        'type' => "region"
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Stalfos Ambush",
        'roomid' => 0x3E,
        'layout' => Region::TOP_RIGHT,
        'type' => "region"
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Conveyor",
        'roomid' => 0x3E,
        'layout' => Region::BOTTOM,
        'type' => "region",
        'switch' => true,
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Conveyor - Bari Key",
        'roomid' => 0x3E,
        'layout' => Region::BOTTOM,
        'type' => 'mob',
        'item' => 'KeyD5',
        'itemset' => ['ice'],
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Conveyor Door",
        'type' => 'keydoor',
        'key' => 'KeyD5',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - IPBJ - orange",
        'roomid' => 0x4E,
        'layout' => Region::TOP_LEFT,
        'type' => "region",
        'peg' => 'orange',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - IPBJ - blue top",
        'roomid' => 0x4E,
        'layout' => Region::TOP_LEFT,
        'type' => "region",
        'peg' => 'blue',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - IPBJ - blue right",
        'roomid' => 0x4E,
        'layout' => Region::TOP_LEFT,
        'type' => "region",
        'peg' => 'blue',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Blob Alley",
        'roomid' => 0x4E,
        'layout' => Region::TOP_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Penguin Line Up",
        'roomid' => 0x6E,
        'layout' => Region::TOP_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Big Spike Cross",
        'roomid' => 0x5E,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Big Spike Cross Door",
        'type' => 'keydoor',
        'key' => 'KeyD5',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Bari University",
        'roomid' => 0x5F,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - H Room right",
        'roomid' => 0x3F,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - H Room center left",
        'roomid' => 0x3F,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - H Room - Key",
        'roomid' => 0x3F,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'standing',
        'item' => 'KeyD5',
        'itemset' => ['ice'],
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - H Room center right",
        'roomid' => 0x3F,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - H Room left",
        'roomid' => 0x3F,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - P Room",
        'roomid' => 0x3F,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Pit Trap",
        'roomid' => 0x5E,
        'layout' => Region::TOP_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Vanilla Ice",
        'roomid' => 0x7E,
        'layout' => Region::RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Vanilla Ice Key Door",
        'type' => 'keydoor',
        'key' => 'KeyD5',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Slime Party",
        'roomid' => 0x8E,
        'layout' => Region::TOP_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Bari Pit left",
        'roomid' => 0x7F,
        'layout' => Region::TOP_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Bari Pit right",
        'roomid' => 0x7F,
        'layout' => Region::TOP_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Big Spikes",
        'roomid' => 0x7F,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Lonely Firebar",
        'roomid' => 0x5E,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Freezor Room",
        'roomid' => 0x7E,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Freezor Room Ledge",
        'roomid' => 0x7E,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Big Chest Room - left",
        'roomid' => 0x9E,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Big Chest Room - right",
        'roomid' => 0x9E,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Block Drop - orange",
        'roomid' => 0x9E,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
        'peg' => 'orange',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Block Drop - left blue",
        'roomid' => 0x9E,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
        'peg' => 'blue',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Block Drop - right blue",
        'roomid' => 0x9E,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
        'peg' => 'blue',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Fairy Drop - orange",
        'roomid' => 0x9E,
        'layout' => Region::TOP_LEFT,
        'type' => "region",
        'peg' => 'orange',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Fairy Drop - blue",
        'roomid' => 0x9E,
        'layout' => Region::TOP_LEFT,
        'type' => "region",
        'peg' => 'blue',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Fairy Drop Door",
        'type' => 'keydoor',
        'key' => 'KeyD5',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Lone Antifairy",
        'roomid' => 0xBE,
        'layout' => Region::TOP_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Block Switch",
        'roomid' => 0xBE,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Block Switch - block",
        'roomid' => 0xBE,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Restock Room Door",
        'type' => 'keydoor',
        'key' => 'KeyD5',
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Restock Room",
        'roomid' => 0xBF,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
        'switch' => true,
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Pottery Barn",
        'roomid' => 0x9F,
        'layout' => Region::BOTTOM_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Pottery Barn Key",
        //'location' => 0x1c17,
        'roomid' => 0x9F,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'pot',
        'item' => 'KeyD5',
        'itemset' => ['ice'],
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Ice Clock",
        'roomid' => 0xAF,
        'layout' => Region::TOP_LEFT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Ice T",
        'roomid' => 0xAE,
        'layout' => Region::TOP_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Over Boss - top",
        'roomid' => 0xCE,
        'layout' => Region::TOP_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Over Boss - pit",
        'roomid' => 0xCE,
        'layout' => Region::TOP_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Map Chest",
        'roomid' => 0x3f,
        'layout' => Region::BOTTOM_LEFT,
        'addresses' => [0xE9DD],
        'type' => 'chest',
        'itemset' => ['ice'],
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Big Key right",
        'roomid' => 0x1F,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Big Key Chest",
        'roomid' => 0x1f,
        'layout' => Region::BOTTOM_RIGHT,
        'addresses' => [0xE9A4],
        'type' => 'chest',
        'itemset' => ['ice'],
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Compass Chest",
        'roomid' => 0x2e,
        'layout' => Region::TOP_RIGHT,
        'addresses' => [0xE9D4],
        'type' => 'chest',
        'itemset' => ['ice'],
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Spike Room",
        'roomid' => 0x5f,
        'layout' => Region::BOTTOM_LEFT,
        'addresses' => [0xE9E0],
        'type' => 'chest',
        'itemset' => ['ice'],
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Freezor Chest",
        'roomid' => 0x7e,
        'layout' => Region::BOTTOM_LEFT,
        'addresses' => [0xE995],
        'type' => 'chest',
        'itemset' => ['ice'],
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Iced T Room",
        'roomid' => 0xae,
        'layout' => Region::TOP_RIGHT,
        'addresses' => [0xE9E3],
        'type' => 'chest',
        'itemset' => ['ice'],
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Big Chest",
        'roomid' => 0x9e,
        'layout' => Region::BOTTOM_LEFT,
        'addresses' => [0xE9AA],
        'type' => 'bigchest',
        'itemset' => ['ice'],
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Boss Room",
        'roomid' => 0xDE,
        'layout' => Region::TOP_RIGHT,
        'type' => "region",
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Boss",
        'addresses' => [0x180157],
        'type' => "drop",
        'itemset' => ['ice'],
    ],
    [
        'group' => 13,
        'name' => "Ice Palace - Prize",
        'addresses' => [
            null,
            0x120A4,
            0x53F5A,
            0x53F5B,
            0x180059,
            0x180073,
            0xC705,
        ],
        'type' => "prize",
        'itemset' => ['prize'],
    ]
];
