<?php

use App\Graph\Region;

return [
    [
        'group' => 7,
        'name' => "Palace of Darkness - Lobby",
        'roomid' => 0x4a,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Left Cage",
        'roomid' => 0x4a,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Middle Cage",
        'roomid' => 0x4a,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Shooter Room",
        'roomid' => 0x09,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Shooter Room Chest",
        'roomid' => 0x09,
        'addresses' => [0xea5b],
        'layout' => Region::TOP_LEFT,
        'type' => 'chest',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Middle Cage Door",
        'type' => 'keydoor',
        'key' => 'KeyD1',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Pit Room",
        'roomid' => 0x3a,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Big Key Chest",
        'roomid' => 0x3a,
        'addresses' => [0xea37],
        'layout' => Region::FULL,
        'type' => 'chest',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Arena Main",
        'roomid' => 0x2a,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Arena North",
        'roomid' => 0x2a,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Arena North Door",
        'type' => 'keydoor',
        'key' => 'KeyD1',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - The Arena - Bridge",
        'roomid' => 0x2a,
        'addresses' => [0xea3d],
        'layout' => Region::FULL,
        'type' => 'chest',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - The Arena - Ledge",
        'roomid' => 0x2a,
        'addresses' => [0xea3a],
        'layout' => Region::FULL,
        'type' => 'chest',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Sexy Statue",
        'roomid' => 0x2b,
        'layout' => Region::LEFT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Map Chest",
        'roomid' => 0x2b,
        'addresses' => [0xea52],
        'layout' => Region::LEFT,
        'type' => 'chest',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Fairies",
        'roomid' => 0x2b,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Conveyor",
        'roomid' => 0x3b,
        'layout' => Region::LEFT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Mimics 1",
        'roomid' => 0x4b,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Jelly Hall",
        'roomid' => 0x4b,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Warp Hint",
        'roomid' => 0x4b,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Warp Room",
        'roomid' => 0x09,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Stalfos Basement",
        'roomid' => 0x0a,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Stalfos Basement Chest",
        'roomid' => 0x0a,
        'addresses' => [0xea49],
        'layout' => Region::FULL,
        'type' => 'chest',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Basement Ledge",
        'roomid' => 0x0a,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Basement Ledge Door",
        'type' => 'keydoor',
        'key' => 'KeyD1',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Falling Bridge Ledge",
        'roomid' => 0x1a,
        'layout' => Region::LEFT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Falling Bridge",
        'roomid' => 0x1a,
        'layout' => Region::LEFT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Falling Bridge Top",
        'roomid' => 0x1a,
        'layout' => Region::LEFT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Falling Bridge Door",
        'type' => 'keydoor',
        'key' => 'KeyD1',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Big Chest Balcony",
        'roomid' => 0x1a,
        'layout' => Region::LEFT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Big Chest",
        'roomid' => 0x1a,
        'addresses' => [0xea40],
        'layout' => Region::LEFT,
        'type' => 'bigchest',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Compass Room",
        'roomid' => 0x1a,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Compass Chest",
        'roomid' => 0x1a,
        'addresses' => [0xea43],
        'layout' => Region::TOP_RIGHT,
        'type' => 'chest',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Compass Room Door",
        'type' => 'keydoor',
        'key' => 'KeyD1',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Harmless Hellway",
        'roomid' => 0x1a,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Harmless Hellway Chest",
        'roomid' => 0x1a,
        'addresses' => [0xea46],
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'chest',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Maze darkness",
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Maze",
        'roomid' => 0x19,
        'layout' => Region::RIGHT,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Maze - Top",
        'roomid' => 0x19,
        'addresses' => [0xea55],
        'layout' => Region::RIGHT,
        'type' => 'chest',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Maze - Bottom",
        'roomid' => 0x19,
        'addresses' => [0xea58],
        'layout' => Region::RIGHT,
        'type' => 'chest',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Basement darkness",
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Basement",
        'roomid' => 0x6a,
        'layout' => Region::RIGHT,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Basement - Left",
        'roomid' => 0x6a,
        'addresses' => [0xea4c],
        'layout' => Region::RIGHT,
        'type' => 'chest',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Basement - Right",
        'roomid' => 0x6a,
        'addresses' => [0xea4f],
        'layout' => Region::RIGHT,
        'type' => 'chest',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Mimics 2",
        'roomid' => 0x1b,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Bow Statue",
        'roomid' => 0x1b,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Pegs darkness",
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Pegs Landing",
        'roomid' => 0x0b,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Pegs",
        'roomid' => 0x0b,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Pegs Door",
        'type' => 'keydoor',
        'key' => 'KeyD1',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Lonely Turtle",
        'roomid' => 0x0b,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Turtle Party",
        'roomid' => 0x0b,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Callback",
        'roomid' => 0x0b,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Alley",
        'roomid' => 0x6a,
        'layout' => Region::RIGHT,
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Dark Alley darkness",
        'type' => 'region',
        'dark' => true,
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Boss Door",
        'type' => 'bigkeydoor',
        'key' => 'BigKeyD1',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Boss Room",
        'roomid' => 0x5a,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Boss",
        'addresses' => [0x180153],
        'type' => 'drop',
        'itemset' => ['pod'],
    ],
    [
        'group' => 7,
        'name' => "Palace of Darkness - Prize",
        'roomid' => 0x5a,
        'addresses' => [0x120a1, 0x53f00, 0x53f01, 0x180056, 0x18007d, 0xc702],
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'prize',
        'itemset' => ['prize'],
    ],

    #Glitched Vertices
    [
        'group' => 7,
        'name' => "Palace of Darkness - Mimics 1 - E/W Camera",
        'roomid' => 0x4b,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
];