<?php

use App\Graph\Region;

return [
    [
        'name' => "Paradox Cave - Top",
        'roomid' => 0xdf,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'name' => "Paradox Cave - Middle",
        'roomid' => 0xef,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'name' => "Paradox Cave - Middle Ledge",
        'roomid' => 0xef,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'name' => "Paradox Cave - Moldorm Room",
        'roomid' => 0xef,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'name' => "Paradox Cave Lower - Far Left",
        'address' => [0xEB2A],
        'roomid' => 0xef,
        'layout' => Region::TOP_RIGHT,
        'type' => 'chest',
        'itemset' => ['lw'],
    ],
    [
        'name' => "Paradox Cave Lower - Left",
        'address' => [0xEB2D],
        'roomid' => 0xef,
        'layout' => Region::TOP_RIGHT,
        'type' => 'chest',
        'itemset' => ['lw'],
    ],
    [
        'name' => "Paradox Cave Lower - Right",
        'address' => [0xEB30],
        'roomid' => 0xef,
        'layout' => Region::TOP_RIGHT,
        'type' => 'chest',
        'itemset' => ['lw'],
    ],
    [
        'name' => "Paradox Cave Lower - Far Right",
        'address' => [0xEB33],
        'roomid' => 0xef,
        'layout' => Region::TOP_RIGHT,
        'type' => 'chest',
        'itemset' => ['lw'],
    ],
    [
        'name' => "Paradox Cave Lower - Middle",
        'address' => [0xEB36],
        'roomid' => 0xef,
        'layout' => Region::TOP_RIGHT,
        'type' => 'chest',
        'itemset' => ['lw'],
    ],
    [
        'name' => "Paradox Cave - Bottom",
        'roomid' => 0xff,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'name' => "Paradox Cave - Bottom Entrance",
        'roomid' => 0xff,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'name' => "Paradox Cave - Shop",
        'roomid' => 0xff,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'name' => "Paradox Cave - Treasure",
        'roomid' => 0xff,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'name' => "Paradox Cave Upper - Left",
        'address' => [0xEB39],
        'roomid' => 0xff,
        'layout' => Region::TOP_RIGHT,
        'type' => 'chest',
        'itemset' => ['lw'],
    ],
    [
        'name' => "Paradox Cave Upper - Right",
        'address' => [0xEB3C],
        'roomid' => 0xff,
        'layout' => Region::TOP_RIGHT,
        'type' => 'chest',
        'itemset' => ['lw'],
    ],
];
