<?php

use App\Graph\Region;


return [
    [
        'group' => 8,
        'name' => "Swamp Palace - Entrance Drained",
        'roomid' => 0x28,
        'layout' => Region::FULL,
        'type' => 'region',
        'peg' => 'orange',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Entrance Filled",
        'roomid' => 0x28,
        'layout' => Region::FULL,
        'type' => 'region',
        'peg' => 'orange',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Entrance Ledge",
        'roomid' => 0x28,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Entrance Chest",
        'type' => 'chest',
        'addresses' => [0xEA9D],
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Entrance Door",
        'type' => 'keydoor',
        'key' => 'KeyD2',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Long Hall",
        'roomid' => 0x38,
        'layout' => Region::LEFT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Long Hall Key",
        'roomid' => 0x38,
        'layout' => Region::LEFT,
        'type' => 'pot',
        'item' => 'KeyD2',
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Long Hall Door",
        'type' => 'keydoor',
        'key' => 'KeyD2',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Hammer Switch overlook",
        'roomid' => 0x37,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Map Chest",
        'type' => 'chest',
        'addresses' => [0xE986],
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Hammer Switch South Drained",
        'roomid' => 0x37,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Hammer Switch South Drained Ledge",
        'roomid' => 0x37,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Water 1",
        'roomid' => 0x37,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Hammer Switch South Filled",
        'roomid' => 0x37,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Hammer Switch South Filled Top Ledge",
        'roomid' => 0x37,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Hammer Switch South Filled Ledge",
        'roomid' => 0x37,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Hammer Switch Ditch",
        'roomid' => 0x37,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Hammer Switch Ditch Key",
        'roomid' => 0x38,
        'layout' => Region::LEFT,
        'type' => 'pot',
        'item' => 'KeyD2',
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Hammer Switch Door",
        'type' => 'keydoor',
        'key' => 'KeyD2',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Hammer Switch",
        'roomid' => 0x37,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Hammer Switch Lever",
        'roomid' => 0x37,
        'layout' => Region::TOP,
        'item' => 'SwampWater1',
        'type' => 'region',
        'itemset' => ['event'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Lobby",
        'roomid' => 0x36,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Lobby Key Ledge",
        'roomid' => 0x36,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Lobby Key Ledge Key",
        'roomid' => 0x36,
        'layout' => Region::FULL,
        'type' => 'pot',
        'item' => 'KeyD2',
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Lobby Joke Ledge",
        'roomid' => 0x36,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Lobby North Ledge",
        'roomid' => 0x36,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Lobby North Ledge Door",
        'type' => 'keydoor',
        'key' => 'KeyD2',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Big Chest",
        'type' => 'bigchest',
        'addresses' => [0xE989],
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Lobby North West Door",
        'type' => 'keydoor',
        'key' => 'KeyD2',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Big O Top",
        'roomid' => 0x46,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Big O Top Left",
        'roomid' => 0x46,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Compass Chest",
        'type' => 'chest',
        'addresses' => [0xEAA0],
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Big O Bottom",
        'roomid' => 0x46,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - West Lever",
        'roomid' => 0x35,
        'layout' => Region::TOP,
        'type' => 'region',
        'item' => 'SwampWater2',
        'switch' => true,
        'itemset' => ['event'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - West Lever Ditch",
        'roomid' => 0x35,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - West Lever Key",
        'roomid' => 0x35,
        'layout' => Region::TOP,
        'type' => 'pot',
        'item' => 'KeyD2',
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Water 2",
        'roomid' => 0x37,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Money Ledge",
        'roomid' => 0x35,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Big Key Chest",
        'type' => 'chest',
        'addresses' => [0xEAA6],
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - West Moat - orange",
        'roomid' => 0x35,
        'layout' => Region::BOTTOM,
        'type' => 'region',
        'peg' => 'orange',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - West Moat Top - blue",
        'roomid' => 0x35,
        'layout' => Region::BOTTOM,
        'type' => 'region',
        'peg' => 'blue',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - West Moat Bottom - blue",
        'roomid' => 0x35,
        'layout' => Region::BOTTOM,
        'type' => 'region',
        'peg' => 'blue',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - West Moat Bottom Left",
        'roomid' => 0x35,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - West Wing",
        'roomid' => 0x34,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - West Wing Left Ledge",
        'roomid' => 0x34,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - West Wing Right Ledge - orange",
        'roomid' => 0x34,
        'layout' => Region::FULL,
        'type' => 'region',
        'peg' => 'orange',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - West Wing Right Ledge - blue",
        'roomid' => 0x34,
        'layout' => Region::FULL,
        'type' => 'region',
        'peg' => 'blue',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - West Wing Attic",
        'roomid' => 0x54,
        'layout' => Region::FULL,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - West Chest",
        'type' => 'chest',
        'addresses' => [0xEAA3],
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Statue Puzzle",
        'roomid' => 0x26,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Forgotten Room",
        'roomid' => 0x26,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Little Spoon",
        'roomid' => 0x26,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Big Spoon",
        'roomid' => 0x26,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Toilet Right",
        'roomid' => 0x76,
        'layout' => Region::TOP_RIGHT,
        'item' => 'SwampWater3',
        'type' => 'region',
        'itemset' => ['event'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Toilet Left",
        'roomid' => 0x76,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Toilet Bowl",
        'roomid' => 0x76,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Thin Hallway",
        'roomid' => 0x76,
        'layout' => Region::LEFT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Flooded Room Top",
        'roomid' => 0x76,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Flooded Room",
        'roomid' => 0x76,
        'layout' => Region::BOTTOM_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Flooded Room - Left",
        'type' => 'chest',
        'addresses' => [0xEAA9],
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Flooded Room - Right",
        'type' => 'chest',
        'addresses' => [0xEAAC],
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Waterfall Room",
        'roomid' => 0x66,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Waterfall Room Chest",
        'type' => 'chest',
        'addresses' => [0xEAAF],
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Waterfall Joke",
        'roomid' => 0x66,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Waterfall Exit",
        'roomid' => 0x66,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Tic Room C",
        'roomid' => 0x16,
        'layout' => Region::TOP_RIGHT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Tic Room I",
        'roomid' => 0x16,
        'layout' => Region::TOP,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Tic Room T",
        'roomid' => 0x16,
        'layout' => Region::TOP_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Pool",
        'roomid' => 0x16,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Pool Left Ledge",
        'roomid' => 0x16,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Pool Door",
        'type' => 'keydoor',
        'key' => 'KeyD2',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Pool Center Ledge",
        'roomid' => 0x16,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Pool Right Ledge",
        'roomid' => 0x16,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Pool Key Ledge",
        'roomid' => 0x16,
        'layout' => Region::BOTTOM,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Pool Key Ledge Key",
        'roomid' => 0x16,
        'layout' => Region::BOTTOM,
        'type' => 'pot',
        'item' => 'KeyD2',
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Boss Room",
        'roomid' => 0x06,
        'layout' => Region::BOTTOM_LEFT,
        'type' => 'region',
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Boss",
        'addresses' => [0x180154],
        'type' => 'drop',
        'itemset' => ['swamp'],
    ],
    [
        'group' => 8,
        'name' => "Swamp Palace - Prize",
        'addresses' => [null, 0x120A0, 0x53F6C, 0x53F6D, 0x180055, 0x180071, 0xC701],
        'type' => 'prize',
        'itemset' => ['prize'],
    ],
];
